### PR TITLE
General data repo

### PR DESCRIPTION
**Pull request by Youbadawy**
**Changes**
General Idea is to prepare a general dictionary with all configuration information inside, a bit like the config.py file created. So what I added in this current commit is composed of the following functionality,

1- config.json (where all important information and targets are listed, like exchange api, and secret phrase, communication channels when we prepare to get the agent live, and the target stocks or pairs)
2- Ways and methods to load the configuration files when called upon (configuration.py)
3- certain other functionalities that will be used further down the line for interacting with the data

**Target**
To better understand these current changes, one must understand my aim, We currently undergo numerous requests and redundancy in downloading the same data (10 year periods) which are not small. the aim to make a local repository with the downloaded data, and on the daily just update the current data repository.
This data will be utilized for

1- Training the Agents,
2- Testing the trained Agents
3- Further Predictions performed by the Agents

4- Analysis of the predictions, 
5- Backtesting agent predictions and actions
6- Analysis of indicators and further prediction features

As we can see this data is essential and will be utilized on numerous instances during our implementations and research. it would be quite inefficient to download them on the daily. 

I also prepared the functionality needed to perform the same as the YahooDownloader but for Crypto exchanges using a module called CCXT (incorporates 100+ of the main crypto exchanges)

@BruceYanghy @XiaoYangLiu-FinRL @spencerR1992 @louisowen6

### CODE REVIEW

**Comment by XiaoYangLiu-FinRL** [comment]
@Youbadawy Very impressive!!  I went over once.  Notice there is a small discrepancy in the finrl/misc.py file, as indicated by github.  Thanks very much for your contributions.

**Comment by spencerR1992** [comment]
Hi @Youbadawy thanks for this contribution!

I'm wondering if we could consider scoping down this PR and planning to add the rest of the functionality later?
For instance, I want to make sure that all these contributions get enjoyed, but we need documentation, and integration into the core functionality o the project.  

initially, I think maybe logging might be a good first step?

Alternatively, creating some kind of training script leveraging your amazing configuration work might also be a good target?

I think all these ideas are great, but I want to make sure we consider them individually to make the best local decisions for each :) 
Thoughts?

**Comment by Youbadawy** [comment]
> 
> 
> Hi @Youbadawy thanks for this contribution!
> 
> I'm wondering if we could consider scoping down this PR and planning to add the rest of the functionality later?
> For instance, I want to make sure that all these contributions get enjoyed, but we need documentation, and integration into the core functionality o the project.
> 
> initially, I think maybe logging might be a good first step?
> 
> Alternatively, creating some kind of training script leveraging your amazing configuration work might also be a good target?
> 
> I think all these ideas are great, but I want to make sure we consider them individually to make the best local decisions for each :)
> Thoughts?

Hello Spencer, glad you guys like the ideas,

I was on the way now to make the YahooDownloader work with the configuration and download the needed Data in a user repository, where the data will be fetched from there and updated. 

Please do let me know how would you like to divide the PR, I could merge the configuration functionality with the downloader module, and create a training script/notebook that displays its use. 

If we were to create this PR for the logger only, how would you like it to be represented and how would you like to merge it with the current project,

in my opinion the logger wouldn't add much functionality for the users, as much as merging your current config.py to the config.json files in order to be able to merge all configurations in one area. 

Please do let me know what you think, and let me know of your vision as I am quite new so I might not see the whole picture and needs as you!

**Comment by spencerR1992** [comment]
I think doing the configuration + yahoodownloader additions is a great start!

**Comment by Youbadawy** [comment]
Hello All, I have created a small script called testing_download.py in main folder to showcase the introduced functionality, 

basically in quick steps:

1- Create user directory to store trained agents, historical data, notebooks, and backtest results
2- download data based on config file information or ARGS passed in that overides config data,
3- fetch that data into an organized df with date/time as index

what is missing,

on the older project, we need to organize the previous methods and classes to feed in into this folder to have everythign organized and tidy. 

I currently started arranging the YahooDownloader option to do the same exact process, download 10 year data into folder, and fetch from that... Please note that I have not changed your old files, kept them the same, just added my own, please do not hesitate to get in contact with me over slack in case of any further clarifications, inquiries, or modifications! 

Looking forward to hearing from you!

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks for the updates.

Btw, the link for slack channel AI4Finance is:  https://app.slack.com/client/T01GYDU6KB6/D01GKP2BG5U

**Comment by Youbadawy** [comment]
The last commit added the same functionality to the yfinance api, as if its its own exchange called yahoo.

**Review by Youbadawy — COMMENTED** [review]
user_data/*

**Comment by Youbadawy** [comment]
Hello Everyone, I will close this pull request and merge everything from my masters repo to your masters! hope you it adds value!

good day!

**Pull request closed without merging**
