### PR TITLE
Allow for automatic saving each N steps

### PR DESCRIPTION
**Pull request by carlogrisetti**
This allows to launch a training and automatically save a model each N steps performed (to manually pick a specific model progress in time)

### CODE REVIEW

**Comment by BruceYanghy** [comment]
Appreciate the commit, but this code is a bit breakable. Thanks.

**Comment by carlogrisetti** [comment]
Ok then, It was a quick fix I did on my env to do that, and understand this is absolutely not the best way to do that.
How would you implement that in a cleaner way?

**Comment by BruceYanghy** [comment]
I don't think we need to save the model by steps, that doesn't make sense. we can just do a model.save after the model is fully trained.

**Comment by carlogrisetti** [comment]
Ok, that is different.y purpose is to be able to pick a model in time, by choosing the best performance it had in a test run, that might not coincide with the best training run.

I'm still "new" to RL, but as I understand the same train/test logic used in supervised ML applies here, albeit with a much lower and non direct impact.

If instead this is not useful at all, just forget this PR :)

**Comment by robzsaunders** [comment]
Hey @carlogrisetti, been reading through PR's and Issues and i don't think this is a dumb idea and infact a really good idea.

What if you're spending 4 weeks training a huge model on lower end hardware? One power outage or a trip on a cable and *poof*

What if you want to compare the last 50 generations?

There's lots of reasons to do this, did you find a cleaner way to implement saving training progress?

**Pull request closed without merging**
