### PR TITLE
Add SDAX, TecDAX, and MDAX

### PR DESCRIPTION
**Pull request by M-Colley**

### CODE REVIEW

**Comment by XiaoYangLiu-FinRL** [comment]
@M-Colley Could you please add some simple description?  I am not sure whether understand it fully and properly.

**Comment by M-Colley** [comment]
Sure. The SDAX ist the small cap DAX, the MDAX is the Mid cap DAX and the TecDAX is the Technological DAX. These are, thus, also indices such as the NASDAQ etc.

**Review by spencerR1992 — APPROVED** [review]
I'm good with this merge!

**Comment by spencerR1992** [comment]
@M-Colley can you please assist us with future such additions and create some kind of documentation as to the descriptions of these indexes in the README or other documentation? Other users would appreciate that kind of documentation

**Comment by M-Colley** [comment]
Sure, will do :)

**Pull request merged**
